"""Render a row workflow configuration from a workflow spec."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

import tomli_w

from .spec import WorkflowSpec


def render_row_workflow(
    spec: WorkflowSpec,
    output_path: str | Path,
    default_command: Optional[str] = None,
) -> Path:
    """Render a ``workflow.toml`` for `row <https://row.readthedocs.io>`_.

    The generated file contains:

    * ``[workspace]`` — signac value file path.
    * ``[default.action]`` — global Row defaults from ``[row.default.action]``
      in the pipeline config (account, setup scripts, default resources, …).
    * ``[[action]]`` entries in topological order, each with:

      - ``name`` and ``command``
      - ``products`` (from ``outputs``)
      - ``previous_actions`` — wired automatically from grubicy dependencies so
        Row gates downstream stages until upstream jobs are complete
      - ``[action.resources]`` (walltime, threads, GPUs …)
      - ``[action.submit_options.<cluster>]`` (account, SBATCH flags, …)
      - ``[action.group]`` with the ``/action == <name>`` include filter plus
        optional ``maximum_size`` / ``submit_whole``

    Parameters
    ----------
    spec
        Validated workflow specification.
    output_path
        Where to write the workflow TOML.
    default_command
        Template used when an action does not define ``runner``.
        ``{name}`` is substituted with the action name and ``{directory}``
        is kept as-is for Row to fill in.
        Defaults to ``"python actions/{name}.py {directory}"``.

    Returns
    -------
    Path
        The path that was written.
    """
    default_command = default_command or "python actions/{name}.py {directory}"
    out_path = Path(output_path)

    doc: Dict[str, Any] = {}

    # [workspace]
    doc["workspace"] = {"value_file": spec.workspace.value_file}

    # [default.action] — forwarded verbatim from [row.default.action] in pipeline config
    if spec.row_defaults:
        doc["default"] = {"action": spec.row_defaults}

    # [[action]] entries in dependency order
    actions: List[Dict[str, Any]] = []
    for action in spec.topological_actions():
        command = action.runner or default_command.format(
            name=action.name, directory="{directory}"
        )
        entry: Dict[str, Any] = {"name": action.name, "command": command}

        if action.outputs:
            entry["products"] = list(action.outputs)

        # previous_actions lets Row gate downstream stages on upstream completion
        if action.dependency:
            entry["previous_actions"] = [action.dependency.action]

        if action.resources:
            entry["resources"] = action.resources

        if action.submit_options:
            entry["submit_options"] = action.submit_options

        # group: always add the /action include filter; optionally batch size
        group: Dict[str, Any] = {}
        if action.group_maximum_size is not None:
            group["maximum_size"] = action.group_maximum_size
        if action.group_submit_whole:
            group["submit_whole"] = True
        group["include"] = [{"condition": ["/action", "==", action.name]}]
        entry["group"] = group

        actions.append(entry)

    doc["action"] = actions

    content = "# Generated by grubicy\n" + tomli_w.dumps(doc)
    out_path.write_text(content, encoding="utf-8")
    return out_path
