"""Render a row workflow configuration from a workflow spec."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

import tomli_w

from .spec import ActionSpec, WorkflowSpec

_DEFAULT_COMMAND = "python actions/{name}.py {directory}"


def _workspace_section(spec: WorkflowSpec) -> Dict[str, Any]:
    return {"value_file": spec.workspace.value_file}


def _default_section(spec: WorkflowSpec) -> Dict[str, Any]:
    return {"action": spec.row_defaults} if spec.row_defaults else {}


def _action_group(action: ActionSpec) -> Dict[str, Any]:
    # Default to 1 directory per job — the only safe default for heterogeneous
    # HPC workloads where each directory may carry a different walltime budget.
    # Override with group.maximum_size in pipeline.toml.
    return {
        "maximum_size": action.group_maximum_size if action.group_maximum_size is not None else 1,
        **({"submit_whole": True} if action.group_submit_whole else {}),
        "include": [{"condition": ["/action", "==", action.name]}],
    }


def _action_entry(action: ActionSpec, default_command: str) -> Dict[str, Any]:
    command = action.runner or default_command.format(
        name=action.name, directory="{directory}"
    )
    return {
        "name": action.name,
        "command": command,
        **({"products": list(action.outputs)} if action.outputs else {}),
        # previous_actions gates downstream stages on upstream completion
        **({"previous_actions": [action.dependency.action]} if action.dependency else {}),
        **({"resources": action.resources} if action.resources else {}),
        **({"submit_options": action.submit_options} if action.submit_options else {}),
        "group": _action_group(action),
    }


def render_row_workflow(
    spec: WorkflowSpec,
    output_path: str | Path,
    default_command: Optional[str] = None,
) -> Path:
    """Render a ``workflow.toml`` for `row <https://row.readthedocs.io>`_.

    The generated file contains:

    * ``[workspace]`` — signac value file path.
    * ``[default.action]`` — global Row defaults from ``[row.default.action]``
      in the pipeline config (account, setup scripts, default resources, …).
    * ``[[action]]`` entries in topological order, each with:

      - ``name`` and ``command``
      - ``products`` (from ``outputs``)
      - ``previous_actions`` — wired automatically from grubicy dependencies so
        Row gates downstream stages until upstream jobs are complete
      - ``[action.resources]`` (walltime, threads, GPUs …)
      - ``[action.submit_options.<cluster>]`` (account, SBATCH flags, …)
      - ``[action.group]`` with the ``/action == <name>`` include filter plus
        optional ``maximum_size`` / ``submit_whole``

    Parameters
    ----------
    spec
        Validated workflow specification.
    output_path
        Where to write the workflow TOML.
    default_command
        Template used when an action does not define ``runner``.
        ``{name}`` is substituted with the action name and ``{directory}``
        is kept as-is for Row to fill in.
        Defaults to ``"python actions/{name}.py {directory}"``.

    Returns
    -------
    Path
        The path that was written.
    """
    cmd = default_command or _DEFAULT_COMMAND
    default = _default_section(spec)
    doc: Dict[str, Any] = {
        "workspace": _workspace_section(spec),
        **({"default": default} if default else {}),
        "action": [_action_entry(a, cmd) for a in spec.topological_actions()],
    }

    out_path = Path(output_path)
    out_path.write_text("# Generated by grubicy\n" + tomli_w.dumps(doc), encoding="utf-8")
    return out_path
